[config]
reload_apps = false

[config.wallpaper]
command = "awww img --transition-type center {{ image }}"
set = true

[templates.waybar]
input_path = "./templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"
# post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = "./templates/config.rasi"
output_path = "~/.config/rofi/config.rasi"

[templates.hyprland]
input_path = "./templates/colors.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.quickshell]
input_path = "./templates/theme.qml"
output_path = "~/.config/quickshell/theme/Theme.qml"

[templates.termusic]
input_path = "./templates/termusic.yml"
output_path = "~/.config/termusic/themes/matugen.yml"
