;; Global WM Settings

[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
; Used for top aligned bars
margin-bottom = 0

; Adjust the _NET_WM_STRUT_PARTIAL bottom value
; Used for bottom aligned bars
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Bar Settings

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false

override-redirect = false

top = true
fixed-center = true
width = 100%
height = 30
offset-x = 0%
offset-y = 0%

background = ${color.background}
foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 2
line-color = ${color.primary}

border-bottom-size = 2
border-bottom-color = ${color.primary}

padding = 0

module-margin-left = 2
module-margin-right = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

font-0 = "Cascadia Code:size=10;3"
font-1 = "feather:size=12;3"

modules-left = workspaces
modules-center = title
modules-right = wireless-network xkeyboard battery alsa backlight date
; launcher sysmenu

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

separator = 
dim-value = 1.0
wm-name = 
locale = 

tray-position = none
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
wm-restack = i3
enable-ipc = true

click-left = 
click-middle = 
click-right =
double-click-left =
double-click-middle =
double-click-right =

cursor-click = 
cursor-scroll = 

;; WM Workspace Specific

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Application Settings

[settings]
throttle-output = 5
throttle-output-for = 10

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/alsa]
type = internal/alsa

master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master

interval = 5

;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume> <label-volume>

;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>
format-muted-prefix = 

;   %percentage% (default)
label-volume = %percentage%%

;   %percentage% (default)
label-muted = " Muted (%percentage%%)"
label-muted-foreground = ${color.foreground-alt}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

ramp-headphones-0 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/backlight]
type = internal/backlight

card = intel_backlight

;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>

;   %percentage% (default)
label = %percentage%%

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

battery = BAT0
adapter = ACAD

poll-interval = 2

time-format = %H:%M:%S

;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <label-charging>
format-charging-prefix = " "

;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <label-discharging>
format-discharging-prefix = " "

;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-prefix = " "

;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %percentage%% %time%

;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%% %time%

;   %percentage% (default)
label-full = %percentage%%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
;bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 

; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
;;animation-discharging-0 = ${battery.anim0}
;;animation-discharging-1 = ${battery.anim1}

; Framerate in milliseconds
;animation-discharging-framerate = 500

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date

interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = "%a %d/%m/%Y"

; Optional time format
time = "%H:%M:%S"

; Available tags:
;   <label> (default)
format = <label>

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %time% %date%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wireless-network]
type = internal/network
interface = wlp1s0

interval = 1.0
ping-interval = 3
accumulate-stats = true
unknown-as-up = true

;   <label-connected> (default)
;   <ramp-signal>
format-connected = <label-connected>
format-connected-prefix = 

;   <label-disconnected> (default)
format-disconnected = <label-disconnected>
format-disconnected-prefix = 

;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: %ifname% %local_ip%
label-connected = "%{A1:networkmanager_dmenu &:} %essid%: %signal%%{A}"

;   %ifname%    [wireless+wired]
; Default: (none)
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false
interval = 5

;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume> <label-volume>

;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>
format-muted-prefix = 

;   %percentage% (default)
label-volume = %percentage%%

; Available tokens:
;   %percentage% (default
label-muted = " Muted"
label-muted-foreground = ${color.foreground-alt}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/keyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

;   <label-layout> (default)
;   <label-indicator> (default)
format = <label-layout> <label-indicator>
format-prefix = 

;   %layout%
;   %name%
;   %number%
; Default: %layout%
label-layout = " %layout%"

;   %name%
; Default: %name%
label-indicator-on = %name%
label-indicator-on-foreground = ${color.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/title]
type = internal/xwindow

format = <label>
format-prefix = 

label = " %title%"
label-maxlen = 30

label-empty = I3 Window Manager

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true
enable-scroll = true

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;10
icon-default = +

format = <label-state>
format-padding = 0

label-monitor = %name%
label-active = %icon%
label-active-foreground = ${color.primary}
label-active-overline = ${color.primary}
label-occupied = %icon%
label-occupied-foreground = ${color.alternate}
label-urgent = %icon%
label-urgent-foreground = ${color.secondary}
label-empty = %icon%
label-active-padding = 2
label-urgent-padding = 2
label-occupied-padding = 2
label-empty-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout> <label-indicator>
format-spacing = 0

label-layout = %name%
label-layout-padding = 2
label-layout-background = ${color.background}
label-layout-foreground = ${color.foreground}

[module/mpd]
type = internal/mpd

host = "127.0.0.1"
port = "6600"
password = "eindrei"

; Seconds to sleep between progressbar/song timer sync
; Default: 1
;; interval = 2

; Available tags:
;   <label-song> (default)
;   <label-time>
;   <bar-progress>
;   <toggle> - gets replaced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-random>
;   <icon-repeat>
;   <icon-repeatone> (deprecated)
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
;   <icon-consume>
;   <icon-prev>
;   <icon-stop>
;   <icon-play>
;   <icon-pause>
;   <icon-next>
;   <icon-seekb>
;   <icon-seekf>
format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next> <icon-repeat> <icon-random> <label-time> <label-song>
format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = ${self.format-online}

; Available tags:
;   <label-offline>
; Default: ""
format-offline = <label-offline>

; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; Default: %artist% - %title%
label-song = 𝄞 %artist% - %title%

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
label-time = %elapsed% / %total%

; Available tokens:
;   None
label-offline = 🎜 mpd is offline

; Only applies if <icon-X> is used
icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
icon-single = 🔂
icon-consume = ✀

[bar]
fill = 
empty = 
indicator = ⏽
; Nerd font :   ,  ⏽,  樂 籠 錄 , 雷 絛

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]
background = #000000
background-alt = #101010
foreground = #FFFFFF
foreground-alt = #8F8F8F
module-fg = #FFFFFF
primary = #62aeef
secondary = #62aeef
alternate = #62aeef
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
